map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name 65-1-246-232.sslip.io 65.1.246.232;

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Redirect all HTTP to HTTPS (except LE challenge)
    location / {
        return 301 https://65-1-246-232.sslip.io$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 65-1-246-232.sslip.io;

    ssl_certificate     /etc/letsencrypt/live/65-1-246-232.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/65-1-246-232.sslip.io/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    proxy_buffering    off;
    proxy_buffer_size  128k;
    proxy_buffers      4 256k;

    location / {
        proxy_pass         http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout    3600s;
        proxy_send_timeout    3600s;
        proxy_connect_timeout   60s;
    }
}
