#!/bin/bash
# ================================================================
# ShopifyLiveCallSystem — AWS EC2 Ubuntu 22.04 Setup Script
# Run this ONCE on a fresh EC2 instance after SSH-ing in.
# Usage: bash setup-server.sh
# ================================================================
set -e  # exit on any error

APP_DIR="/home/ubuntu/app"
APP_PORT=3000

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   ShopifyLiveCallSystem — Server Setup       ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── 1. System update ────────────────────────────────────────────
echo "▶ Step 1/7: Updating system packages..."
sudo apt update -y && sudo apt upgrade -y
sudo apt install -y curl git unzip build-essential ufw

# ── 2. Node.js 20 LTS ───────────────────────────────────────────
echo "▶ Step 2/7: Installing Node.js 20 LTS..."
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt install -y nodejs
echo "   Node: $(node -v) | npm: $(npm -v)"

# ── 3. PM2 (process manager) ────────────────────────────────────
echo "▶ Step 3/7: Installing PM2..."
sudo npm install -g pm2
pm2 startup systemd -u ubuntu --hp /home/ubuntu | tail -1 | sudo bash || true

# ── 4. Nginx ────────────────────────────────────────────────────
echo "▶ Step 4/7: Installing Nginx..."
sudo apt install -y nginx
sudo systemctl enable nginx

# ── 5. coturn (TURN/STUN server) ────────────────────────────────
echo "▶ Step 5/7: Installing coturn..."
sudo apt install -y coturn
sudo sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

# Generate a random TURN secret
TURN_SECRET=$(openssl rand -hex 32)
PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)

sudo tee /etc/turnserver.conf > /dev/null <<TURNCONF
# coturn config — generated by setup-server.sh
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
external-ip=${PUBLIC_IP}
min-port=49152
max-port=65535
use-auth-secret
static-auth-secret=${TURN_SECRET}
realm=vaama.live
fingerprint
verbose
log-file=/var/log/coturn.log
TURNCONF

sudo systemctl restart coturn
sudo systemctl enable coturn

echo "   ✅ coturn running | Public IP: ${PUBLIC_IP}"
echo "   ✅ TURN secret: ${TURN_SECRET}  ← save this!"

# ── 6. App directory ────────────────────────────────────────────
echo "▶ Step 6/7: Setting up app directory..."
mkdir -p "$APP_DIR"
mkdir -p "$APP_DIR/data"
chown -R ubuntu:ubuntu "$APP_DIR"

# ── 7. Nginx config ─────────────────────────────────────────────
echo "▶ Step 7/7: Configuring Nginx reverse proxy..."
sudo tee /etc/nginx/sites-available/livecall > /dev/null <<NGINXCONF
server {
    listen 80;
    server_name ${PUBLIC_IP} _;

    # WebSocket support (required for Socket.IO)
    location / {
        proxy_pass         http://localhost:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
NGINXCONF

sudo ln -sf /etc/nginx/sites-available/livecall /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx

# ── 8. Firewall (UFW) ───────────────────────────────────────────
echo "▶ Configuring firewall..."
sudo ufw allow 22/tcp    # SSH
sudo ufw allow 80/tcp    # HTTP
sudo ufw allow 443/tcp   # HTTPS
sudo ufw allow 3478/udp  # TURN UDP
sudo ufw allow 3478/tcp  # TURN TCP
sudo ufw allow 5349/tcp  # TURNS TLS
sudo ufw allow 5349/udp  # TURNS TLS UDP
sudo ufw allow 49152:65535/udp  # TURN relay ports
sudo ufw --force enable

# ── Done ────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   ✅ Server setup complete!                              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Public IP  : ${PUBLIC_IP}"
echo "  TURN secret: ${TURN_SECRET}"
echo "  App dir    : ${APP_DIR}"
echo ""
echo "  NEXT: Run deploy.bat on your Windows machine to push the app."
echo "  Then SSH back in and run: cd ~/app && bash start-app.sh"
echo ""
echo "  ⚠  Save your TURN secret — add it to .env as TURN_CREDENTIAL"
echo ""
